# -*- coding: utf-8 -*-
"""Part C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opD_KMOFDP1PERuQxg2mZ45l0MUsxcQf

### Q1: Bias-Variance Tradeoff

- **Decision Trees (High Variance)**: A single tree can grow deep enough to memorize specific noise in the training data. This leads to **low bias** (fits training data well) but **high variance** (small changes in data result in a completely different tree and poor generalization).
- **Random Forest (Lower Variance)**: Uses **Bagging** (Bootstrap Aggregating) to train multiple trees on different subsets of data. By averaging the results, the individual errors (variance) of the trees cancel each other out, while the low bias is largely preserved.

**Bagging Diagram Concept:**
```
Original Dataset -> [Subset A] -> [Tree 1] \
                 -> [Subset B] -> [Tree 2] -- (Average/Voting) -> Final Prediction
                 -> [Subset C] -> [Tree 3] /
```
"""

import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

def plot_overfitting_curve(X, y, max_depths):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    train_accs, test_accs = [], []

    for d in max_depths:
        model = DecisionTreeClassifier(max_depth=d, random_state=42)
        model.fit(X_train, y_train)
        train_accs.append(accuracy_score(y_train, model.predict(X_train)))
        test_accs.append(accuracy_score(y_test, model.predict(X_test)))

    plt.figure(figsize=(10, 6))
    plt.plot(max_depths, train_accs, label='Train Accuracy', marker='o')
    plt.plot(max_depths, test_accs, label='Test Accuracy', marker='s')
    plt.xlabel('Max Depth')
    plt.ylabel('Accuracy')
    plt.title('Decision Tree: Training vs. Testing Accuracy')
    plt.legend()
    plt.grid(True)
    plt.show()

    optimal_depth = max_depths[np.argmax(test_accs)]
    print(f'Optimal Depth based on Test Accuracy: {optimal_depth}')

plot_overfitting_curve(X, y, range(1, 16))

"""### Q3: Debugging Identical Accuracy

Identical train and test accuracy (0.95) is **unusual but not necessarily an error**, depending on the context:

1. **Data Leakage (Problem)**: The most likely cause. If training data leaked into the test set (e.g., overlapping indices), the model is just predicting on data it has already seen.
2. **Small Dataset (Problem)**: If the test set is very small, the metrics might coincide by chance, but they aren't statistically robust.
3. **Perfect Generalization (Unlikely)**: While 0.95 is good, usually training accuracy is at least slightly higher than test accuracy. If they are exactly the same, check if you used `X_train` for both evaluation steps by mistake.
"""