# -*- coding: utf-8 -*-
"""Part A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opD_KMOFDP1PERuQxg2mZ45l0MUsxcQf
"""

import pandas as pd
import numpy as np

np.random.seed(42)

n_records = 2000

data = {
    'annual_income': np.random.normal(65000, 25000, n_records).clip(20000, 200000),
    'credit_score': np.random.randint(300, 850, n_records),
    'loan_amount': np.random.normal(15000, 10000, n_records).clip(1000, 50000),
    'employment_years': np.random.randint(0, 40, n_records),
    'debt_to_income': np.random.uniform(0.1, 0.6, n_records),
    'num_credit_cards': np.random.randint(1, 15, n_records)
}

df = pd.DataFrame(data)

score = (
    (df['credit_score'] - 300) / 550 * 0.5 +
    (df['annual_income'] / 200000) * 0.3 -
    (df['debt_to_income']) * 0.2
)


score += np.random.normal(0, 0.1, n_records)


df['approved'] = (score > 0.4).astype(int)

display(df.head())
print(f'\nApproval distribution:\n{df["approved"].value_counts(normalize=True)}')

from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.model_selection import train_test_split

X = df.drop('approved', axis=1)
y = df['approved']


dt = DecisionTreeClassifier(max_depth=4, random_state=42)
dt.fit(X, y)


tree_rules = export_text(dt, feature_names=list(X.columns))
print('Decision Tree Rules Summary:')
print(tree_rules)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


param_dist = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}


rf = RandomForestClassifier(random_state=42)


rf_random = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)


rf_random.fit(X_train, y_train)


print(f"Best Parameters: {rf_random.best_params_}")
print(f"Best CV Score: {rf_random.best_score_:.4f}")
print(f"Test Set Accuracy: {rf_random.score(X_test, y_test):.4f}")