# -*- coding: utf-8 -*-
"""Part D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opD_KMOFDP1PERuQxg2mZ45l0MUsxcQf

# Model Comparison Task

**Prompt:** Create a matplotlib visualization comparing Decision Tree, Random Forest, and Logistic Regression models for the synthetic loan approval dataset.

### Objectives:
1. Train a **Logistic Regression** model as a baseline.
2. Evaluate **Accuracy**, **F1-Score**, and **ROC-AUC** for all models.
3. Generate a grouped bar chart to visualize performance differences.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)
lr_probs = lr_model.predict_proba(X_test)[:, 1]


comparison_data = {
    'Metric': ['Accuracy', 'F1-Score', 'ROC-AUC'],
    'Decision Tree': [
        accuracy_score(y_test, dt_preds),
        f1_score(y_test, dt_preds),
        roc_auc_score(y_test, dt_probs)
    ],
    'Random Forest': [
        accuracy_score(y_test, rf_preds),
        f1_score(y_test, rf_preds),
        roc_auc_score(y_test, rf_probs)
    ],
    'Logistic Regression': [
        accuracy_score(y_test, lr_preds),
        f1_score(y_test, lr_preds),
        roc_auc_score(y_test, lr_probs)
    ]
}

comparison_df = pd.DataFrame(comparison_data)
display(comparison_df)

labels = comparison_df['Metric']
x = np.arange(len(labels))
width = 0.25

fig, ax = plt.subplots(figsize=(12, 7))
rects1 = ax.bar(x - width, comparison_df['Decision Tree'], width, label='Decision Tree', color='#3498db')
rects2 = ax.bar(x, comparison_df['Random Forest'], width, label='Random Forest', color='#2ecc71')
rects3 = ax.bar(x + width, comparison_df['Logistic Regression'], width, label='Logistic Regression', color='#e74c3c')

ax.set_ylabel('Scores')
ax.set_title('Model Comparison: DT vs RF vs Logistic Regression')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()
ax.set_ylim(0, 1.1)


def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)
autolabel(rects3)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Comparison Summary
- **Logistic Regression**: Serves as a strong baseline, performing well on linearly separable data.
- **Decision Tree**: Provides high interpretability but may suffer from higher variance.
- **Random Forest**: Generally provides the best predictive power by averaging multiple trees to reduce overfitting.
"""