# -*- coding: utf-8 -*-
"""Part B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opD_KMOFDP1PERuQxg2mZ45l0MUsxcQf
"""

from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import time
import pandas as pd


best_params = rf_random.best_params_

rf_model = RandomForestClassifier(**best_params, random_state=42)
start_rf = time.time()
rf_model.fit(X_train, y_train)
rf_time = time.time() - start_rf

et_model = ExtraTreesClassifier(**best_params, random_state=42)
start_et = time.time()
et_model.fit(X_train, y_train)
et_time = time.time() - start_et

rf_preds = rf_model.predict(X_test)
rf_probs = rf_model.predict_proba(X_test)[:, 1]

et_preds = et_model.predict(X_test)
et_probs = et_model.predict_proba(X_test)[:, 1]

results = {
    "Metric": ["Accuracy", "F1-Score", "ROC-AUC", "Training Time (s)"],
    "Random Forest": [
        accuracy_score(y_test, rf_preds),
        f1_score(y_test, rf_preds),
        roc_auc_score(y_test, rf_probs),
        rf_time
    ],
    "Extra Trees": [
        accuracy_score(y_test, et_preds),
        f1_score(y_test, et_preds),
        roc_auc_score(y_test, et_probs),
        et_time
    ]
}

comparison_df = pd.DataFrame(results)
display(comparison_df)